site_name: 'Git 101'
theme:
  name: 'material'
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
extra_css:
  - stylesheets/title.css

