site_name: "Git 101"
site_url: https://ub-mmi-but.github.io/git-101/
repo_url: https://github.com/ub-mmi-but/git-101/
theme:
  name: 'material'
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.footer
    - navigation.tabs.sticky
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.keys

extra_css:
  - stylesheets/title.css
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
