site_name: 'Git 101'
theme:
  name: 'material'
  features:
    - navigation.expand

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
extra_css:
  - stylesheets/title.css

