site_name: "Git 101"
theme:
  name: "material"
  features:
    - toc.integrate
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
extra_css:
  - stylesheets/title.css
  - stylesheets/mermaid.css
