site_name: "Git 101"
theme:
  name: "material"
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.footer
    - navigation.tabs.sticky
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.keys

extra_css:
  - stylesheets/title.css
  - stylesheets/mermaid.css
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
